### ISSUE TITLE
dev模式打开白屏

### ISSUE THREAD

**Issue by Moonpie413** [zhangzicao/vote_tpb#1]
请问在package.json中使用dev模式打开后白屏, 由解决办法吗

**Comment by zhangzicao** [comment]
信息不足难以分析，我估计出现问题的可能原因有：
1、是因为你直接运行了命令行npm run electron-start看到的白屏。在此之前你需要运行npm run dev打开开发服务器（浏览器上打开的网页会报错，是因为运行环境不在electron应用内）
2、node_modules里的模块问题，建议使用npm重新下载。（可以搜索“electron白屏问题”）
